name: Build Documents

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  convert-docs:
    runs-on: ubuntu-latest
    # This condition checks if the commit message ends with or contains "gerar pdf"
    if: "contains(github.event.head_commit.message, 'gerar pdf')"
    
    container:
      image: pandoc/extra:latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Run Pandoc conversion script
      run: |
        pandoc [0-9].[0-9]_*.md -o tcc.pdf --file-scope -V documentclass=report --top-level-division=chapter
        pandoc [0-9].[0-9]_*.md -o tcc.docx --file-scope -V documentclass=report --top-level-division=chapter

    - name: Upload PDF and DOCX artifacts
      uses: actions/upload-artifact@v4
      with:
        name: converted-documents
        path: |
          tcc.pdf
          tcc.docx
